//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.01 at 09:57:53 PM CET 
//


package se.atg.service.harrykart.java.domain;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import lombok.*;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
@Setter
@ToString
public class Lane
{
    @JacksonXmlProperty
    @XmlValue
    private Integer value;

    @XmlAttribute(name = "number")
    private int number;


    public Integer getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = Integer.parseInt(value);
    }
    public void setValue(int value) {
        this.value = value;
    }
}
